# Generated by Django 3.0 on 2023-05-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='imagges',
        ),
    ]
